const ACTION_TYPES = {
  STORE_ALL_BLOGS: "STORE_ALL_BLOGS",
  STORE_CATEGORY_BLOGS: "STORE_CATEGORY_BLOGS",
  STORE_ACTIVE_BLOG: "STORE_ACTIVE_BLOG",
  STORE_ACTIVE_AUTHOR: "STORE_ACTIVE_AUTHOR",
  STORE_LATEST_BY_USER: "STORE_LATEST_BY_USER",
};

export default ACTION_TYPES;
